sudo: true
services:
- docker
language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@ibuildstuff.co.uk
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- gem build sensu-plugins-azurerm.gemspec
- gem install sensu-plugins-azurerm-*.gem
- bundle exec rake quick
#- bundle exec rake kitchen:ruby-`echo $TRAVIS_RUBY_VERSION | sed -e "s/\.//g"`-debian-8
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: rubygems
  api_key:
    secure: qFtQsZUvfs7kpE2nMfFlBMhYkEfsn6F1k1iXsi68kqRGm1kgv1BhSVhnzvkeD7BM8ZykQNrRaXnod4WHdelwvBoXghjczKNCO0OzyskQEBB0BFHc/Ipn3bl1lJxe7ka+ks8M0wdEJPAbhPncAsLVE3H3do0uby2dLCL87KGrv1OC2VOxLbQjl+lLAK44+Qxzm39wbxJJmdZGIBPjGXRp1DnDroOrXwRgpGZ9LvtuMD5Zpu6FFoxh0S/0Xw9M7Y70V5Zy51NZ3NQn/o+iVp9Lib/w62sRWyhMBvhg0QHJYSn+CoZCpHhOgc3sHzPFTy3OI0fkh9rxmFPYpvI4Mw5U9KngTYf941Rr3SzkjA7v/+zCbfHI9JnzB9E5ndTxbSweh4IG+MI+1xspPORIBKRLOv/rYMo8XgiUplqqB/StW6fz3psIA88Q9N7X02l12pOPX5BHfsxk/c3BO/jNUUWnH9V62N+DLoHJ5My8RLLGw2jpb6Ln/8RPg2HxwwTEaWb7j9+F/ZhSnQ7zPaxGHu1Da/w2dBWGwvFxwVgGM7OXUhq3Cv4iSoupzekFfmdn3SQTSq4ZExlWgUlzwgfTM3Q8OKIcWJv/J81NYXBpu3EwssxN2zD3tw4EySxstlN5FU9H5aqFWMK4NPrz7Hcl0mUOJHKIl/UmuqmRzPR0/8NI9iQ=
  gem: sensu-plugins-azurerm
  on:
    tags: true
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-azurerm
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-load-checks
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1

